version: '3.2'

services:
    db:
        build:
            context: ./postgres
            cache_from:
                - feeder_db:latest
        env_file:
            - ./postgres/.env
        volumes:
            - postgres-data:/var/lib/postgresql/data
    feed:
        build:
          context: .
          cache_from:
            - feeder_feed:latest
        volumes:
            - .:/code
        depends_on:
            - db

volumes:
    postgres-data:
